# Generated by Django 3.1.6 on 2021-05-31 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='GAME_WON',
            field=models.BooleanField(default=False),
        ),
    ]
