# Generated by Django 3.1.6 on 2021-04-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_match_player_1_wins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='numDraws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='numLosses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='numWins',
            field=models.IntegerField(default=0),
        ),
    ]
