# Generated by Django 3.1.6 on 2021-05-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20210528_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='WAITING_FOR_2ND_PLAYER',
        ),
    ]
